# Generated by Django 5.0.6 on 2026-09-04 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity')], max_length=20)),
                ('is_group', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.ledgergroup')),
            ],
            options={
                'db_table': 'Ledger_Groups',
                'ordering': ['company_id', 'parent_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity')], max_length=20)),
                ('ledger_category', models.CharField(max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('opening_balance_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=10)),
                ('bank_account_no', models.CharField(blank=True, max_length=40, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=15, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=15, null=True)),
                ('alias_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=150, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=150, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('state_name', models.CharField(blank=True, max_length=60, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_registration_type', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=15, null=True)),
                ('emirate', models.CharField(blank=True, max_length=30, null=True)),
                ('po_box_no', models.CharField(blank=True, max_length=20, null=True)),
                ('vat_trn_no', models.CharField(blank=True, max_length=20, null=True)),
                ('trade_license_no', models.CharField(blank=True, max_length=30, null=True)),
                ('trade_license_expiry', models.DateField(blank=True, null=True)),
                ('creditor_type', models.CharField(blank=True, max_length=30, null=True)),
                ('airline_code', models.CharField(blank=True, max_length=3, null=True)),
                ('supplier_code', models.CharField(blank=True, max_length=30, null=True)),
                ('office_id', models.CharField(blank=True, max_length=30, null=True)),
                ('tax_category', models.CharField(blank=True, max_length=10, null=True)),
                ('tax_type', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_applicable', models.BooleanField(default=False)),
                ('gst_tax_type', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tds_applicable', models.BooleanField(default=False)),
                ('tds_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hsn_code', models.CharField(blank=True, max_length=15, null=True)),
                ('tcs_applicable', models.BooleanField(default=False)),
                ('tcs_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='accounting.ledgergroup')),
            ],
            options={
                'db_table': 'Ledgers',
            },
        ),
        migrations.AddIndex(
            model_name='ledgergroup',
            index=models.Index(fields=['company_id'], name='Ledger_Grou_company_57452c_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgergroup',
            index=models.Index(fields=['parent'], name='Ledger_Grou_parent__db0219_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgergroup',
            constraint=models.UniqueConstraint(fields=('company_id', 'parent', 'name'), name='uq_ledger_group_company_parent_name'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['company_id'], name='Ledgers_company_cbba92_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['group'], name='Ledgers_group_i_47bd05_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(fields=('company_id', 'name'), name='uq_ledger_company_name'),
        ),
    ]
